/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CALENDAR_AUTODEFS_H
#define CALENDAR_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CALENDAR_NAME "calendar"
#define S3E_EXT_CALENDAR_HASH 0x74878ff

#endif /* !CALENDAR_AUTODEFS_H */
